# Generated by Django 2.2.2 on 2019-07-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcbose', '0002_auto_20190707_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
