# Generated by Django 2.2.2 on 2019-07-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcbose', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='Name_yourself',
        ),
    ]
