# Generated by Django 2.2.2 on 2019-07-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcbose', '0006_auto_20190709_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user1',
            new_name='user',
        ),
    ]
