# Generated by Django 2.2.2 on 2019-07-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcbose', '0007_auto_20190709_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
