# Generated by Django 2.2.2 on 2019-07-10 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcbose', '0008_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Fathers_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='Mobile_no',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Mothers_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='Name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='Resedential_adress',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
