# Generated by Django 2.2.2 on 2019-07-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcbose', '0011_auto_20190710_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Mobile_no',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='Email_id',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
