# Generated by Django 2.2.2 on 2019-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcbose', '0012_auto_20190710_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=10),
        ),
    ]
