# Generated by Django 2.2.2 on 2019-07-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcbose', '0013_auto_20190710_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Resedential_adress',
            new_name='Resedential_address',
        ),
    ]
